// ------------------------------> VARIABLES <------------------------------

let gameSeq = [];    // Stores the sequence generated by the game
let userSeq = [];    // Stores the user's input sequence
let btnsColor = ["red", "green", "blue", "yellow"];    // All possible button colors
let highScoreArr = [];    // Stores high scores (used to calculate the highest score)

let gameStart = false;    // Tells if the game has started or not
let level = 0;    // Current level of the game

let h2 = document.querySelector("h2");    // Heading element to show game status



// --------------------------> GAME START LISTENER <-------------------------

// Start the game when any key is pressed
document.addEventListener("keypress" , function(){

    if( gameStart == false ){
        console.log("Game started...");
        gameStart = true;   
        levelUp();      // Start the game from level 1
    }
    
});



// ------------------------------> LEVEL UP <-------------------------------

function levelUp(){
    userSeq = [];    // Reset user input for the new level
    level++;    // Increase the level count
    h2.innerText = `Level ${level}`;


    // Pick a random color
    let randIdx = Math.floor(Math.random()*4);
    let randColor = btnsColor[ randIdx ];
    let randBtn = document.querySelector(`.${randColor}`)
    

    console.log(`Random Color: ${randColor}`);
    gameSeq.push(randColor);    // Adds the color that was generated by the game to the game sequence
    console.log(`gameSeq = ${gameSeq}`);        

    btnFlash(randBtn);    // Shows a flash effect on the color generated by the game

};



// -----------------------------> FLASH BUTTON <----------------------------

function btnFlash(randBtn){
    randBtn.classList.add("flash");
    setTimeout( function(){
        randBtn.classList.remove("flash");
    }, 250);    // Flash duration = 250ms
};



// --------------------------- USER BUTTON PRESS -------------------------


// Add event listener to all color buttons
let allBtns = document.querySelectorAll(".btn");
for(btn of allBtns){
    btn.addEventListener("click" , btnPress );
};


function btnPress(){
    console.log("Button was pressed...");
    console.log(this);
    let userBtn = this ;   // this = btn ( btn object )

    let userColorName = userBtn.getAttribute("id");
    console.log(`User pressed "${userColorName}" button`);

    userSeq.push(userColorName);    // Add the pressed color to user's sequence
    console.log(`userSeq = ${userSeq}`);
    
    // Add glow effect on press
    userBtn.style.boxShadow = `3px 3px 8px 8px ${userColorName}`;
    setTimeout( function(){
        userBtn.style.boxShadow = "0 0 0 0 black";
    } , 200);


    checkBtnColor(userSeq.length-1);    // Check if the user clicked the right color

};



// -------------------------- CHECK USER INPUT ---------------------------

function checkBtnColor(idx){
    console.log(`Current Level = ${level}`);
    
    // Checks if the user's clicked color matches the game's color at the same step.
    if(userSeq[idx] === gameSeq[idx]){
        console.log("Same color...");

        // If user completed the whole sequence, go to next level
        if( userSeq.length == gameSeq.length ){
            setTimeout( levelUp , 1000 );
        }

    } else {
        // User pressed the wrong color => Game Over

        highScoreArr.push(level);    // Store the score in high score array 
        console.log(`highScoreArr = ${highScoreArr} `);    
        
        
        // Calculate max score using spread operator
        let maxScore = Math.max(...highScoreArr);

    
        /*
        arr.reduce( (args,el)=>{...} );   method was used
        let maxScore = highScoreArr.reduce( (max , currScore)=>{          
                            if( max < currScore ){                        
                                return currScore;                     
                            } else {
                                return max;
                            }                                          
                    });
        */ 


        // Show game over message and high score
        h2.innerHTML = `Game Over! Your score was <b>${level}</b>   <br>  
                        Press any key to start   <br><br>
                        <i> Highest Score is </i> <b>${maxScore}</b>` ;

        
        // Flash red background on wrong input
        document.querySelector("body").style.backgroundColor = "red";
        setTimeout( function(){
            document.querySelector("body").style.backgroundColor = "black";
        }, 200 );

        
        reset();   // Reset the game

    }

};



// ------------------------------- RESET ---------------------------------

function reset(){
    gameStart = false;
    gameSeq = [];
    userSeq = [];
    level = 0
};


